appli:
    resource: "@AppliBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password


utilisation:
    resource: "@AppliBundle/Controller/UtilisationController.php"
    type:     annotation
    prefix:   /admin/

support:
    resource: "@AppliBundle/Controller/SupportController.php"
    type:     annotation
    prefix:   /admin/

diffusion:
    resource: "@AppliBundle/Controller/DiffusionController.php"
    type:     annotation
    prefix:   /admin/

scriptQuestion:
    resource: "@AppliBundle/Controller/ScriptQuestionController.php"
    type:     annotation
    prefix:   /admin/

expertType:
    resource: "@AppliBundle/Controller/expertTypeController.php"
    type:     annotation
    prefix:   /admin/

conseilType:
    resource: "@AppliBundle/Controller/conseilTypeController.php"
    type:     annotation
    prefix:   /admin/