<?php

namespace AppliBundle\Repository;

/**
 * conseilTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class conseilTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
