<?php

namespace AppliBundle\Repository;

/**
 * expertTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class expertTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
