<?php

namespace AppliBundle\Repository;

/**
 * ProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSupports(){
        $qb = $this->createQueryBuilder('p')
            ->leftJoin('p.support', 's')
           ->addSelect('s');

        return $qb->getQuery()->getResult();
    }

    public function getDiffusions(){
        $qb = $this->createQueryBuilder('p')
            ->leftJoin('p.diffusion', 'd')
            ->addSelect('d');

        return $qb->getQuery()->getResult();
    }

    public function getUtilisations(){
        $qb = $this->createQueryBuilder('p')
            ->leftJoin('p.utilisation', 'u')
            ->addSelect('u');

        return $qb->getQuery()->getResult();
    }


}
