<?php

namespace AppliBundle\Repository;

/**
 * ScriptQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScriptQuestionRepository extends \Doctrine\ORM\EntityRepository
{
}
