<?php

namespace AppliBundle\Repository;

/**
 * ScriptReponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScriptReponseRepository extends \Doctrine\ORM\EntityRepository
{
}
