<?php

namespace AppliBundle\Repository;

/**
 * ScriptEcritureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScriptEcritureRepository extends \Doctrine\ORM\EntityRepository
{
}
