<?php

namespace AppliBundle\Repository;

/**
 * ScriptRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScriptRepository extends \Doctrine\ORM\EntityRepository
{
}
